Repository wappalyzer/wappalyzer, pull requests merged in 2022-05, with the labels that each got.

#6224 Add WysiBB / rich text editors
  src/drivers/webextension/images/icons/WysiBB.svg
  src/technologies/w.json
Labels: Technology request

#6226 Add Omurga Sistemi / cms
  src/drivers/webextension/images/icons/Omurga Sistemi.svg
  src/technologies/o.json
Labels: Technology request

#6227 Add ProcessWire / cms
  src/drivers/webextension/images/icons/ProcessWire.svg
  src/technologies/p.json
Labels: Technology request

#6228 Add Dyte / livestreaming, Add WebRTC / miscellaneous
  src/drivers/webextension/images/icons/Dyte.svg
  src/drivers/webextension/images/icons/WebRTC.svg
  src/technologies/d.json
  src/technologies/w.json
Labels: Technology request

#6229 Remove Google Remarketing Tag / retargeting
  src/technologies/g.json
Labels: Bug

#6230 Add ShipTection / shopify-apps #5832
  src/drivers/webextension/images/icons/ShipTection.png
  src/technologies/s.json
Labels: Technology request

#6231 Add Bold apps / shopify-apps #5833
  src/drivers/webextension/images/icons/Bold.svg
  src/technologies/b.json
Labels: Technology request

#6233 Add Kaltura / video-player, livestreaming
  src/drivers/webextension/images/icons/Kaltura.svg
  src/technologies/k.json
Labels: Technology request

#6234 Add JouwWeb / page builders
  src/drivers/webextension/images/icons/JouwWeb.svg
  src/technologies/j.json
Labels: Technology request

#6235 Add Moneris / pp, Add Moneris Payment Gateway / wp plugin
  src/drivers/webextension/images/icons/Moneris.svg
  src/technologies/m.json
Labels: Technology request

#6236 Add Gumroad / ecommerce
  src/drivers/webextension/images/icons/Gumroad.svg
  src/technologies/g.json
Labels: Technology request

#6238 Add LayoutHub / shopify-app, page-builders #5834
  src/drivers/webextension/images/icons/LayoutHub.png
  src/technologies/l.json
Labels: Technology request

#6245 Update Zozo / ecommerce
  src/technologies/z.json
Labels: Bug

#6246 Add The Hotels Network / personalisation, analytics
  src/drivers/webextension/images/icons/The Hotels Network.svg
  src/technologies/t.json
Labels: Technology request

#6275 Update The Events Calendar / wp-plugin
  src/technologies/t.json
Labels: Bug

#6274 Add PurpleAds / advertising
  src/drivers/webextension/images/icons/PurpleAds.svg
  src/technologies/p.json
Labels: Technology request

#6273 Add iAdvize / live-chat
  src/drivers/webextension/images/icons/iAdvize.svg
  src/technologies/i.json
Labels: Technology request

#6272 Update React / js framework
  src/technologies/r.json
Labels: Bug

#6271 Add ReConvert / shopify-apps
  src/drivers/webextension/images/icons/ReConvert.svg
  src/technologies/r.json
Labels: Technology request

#6269 Add Trackify X / shopify-app, analytics #5847
  src/drivers/webextension/images/icons/Trackify X.png
  src/technologies/t.json
Labels: Technology request

#6268 Update Jimdo / cms
  src/drivers/webextension/images/icons/Jimdo.svg
  src/drivers/webextension/images/icons/jimdo.png
  src/technologies/j.json
Labels: Bug

#6267 Add ImageEngine / cdn, performance
  src/drivers/webextension/images/icons/ImageEngine.svg
  src/technologies/i.json
Labels: Technology request

#6266 Add NagaCommerce / ecommerce
  src/drivers/webextension/images/icons/NagaCommerce.svg
  src/technologies/n.json
Labels: Technology request

#6259 Add PickyStory / shopify-app #5846
  src/drivers/webextension/images/icons/PickyStory.png
  src/technologies/p.json
Labels: Technology request

#6258 Add PeerBoard / message-boards #5836
  src/drivers/webextension/images/icons/PeerBoard.png
  src/technologies/p.json
Labels: Technology request

#6257 Add Obsidian Incentivize / shopify-apps #5835
  src/drivers/webextension/images/icons/Obsidian.png
  src/technologies/o.json
Labels: Technology request

#6255 Add Lazada / ecommerce
  src/drivers/webextension/images/icons/Lazada.svg
  src/technologies/l.json
Labels: Technology request

#6254 Add Mindbox / marketing-automation
  src/drivers/webextension/images/icons/Mindbox.png
  src/technologies/m.json
Labels: Technology request

#6249 Add siimple / ui framework
  src/drivers/webextension/images/icons/siimple.svg
  src/technologies/s.json
Labels: Technology request

#6248 Added Azure Front Door
  src/technologies/a.json
Labels: Technology request

#6247 Add Piwik Pro Core / analytics
  src/drivers/webextension/images/icons/Piwik PRO Core.svg
  src/technologies/p.json
Labels: Technology request, Bug

#6278 Add Magazord / ecommerce
  src/drivers/webextension/images/icons/Magazord.svg
  src/technologies/m.json
Labels: Technology request

#6279 Add stores.jp / ecommerce
  src/drivers/webextension/images/icons/stores.jp.svg
  src/technologies/s.json
Labels: Technology request

#6280 Add Letro / reviews, content-curation
  src/drivers/webextension/images/icons/Letro.svg
  src/technologies/l.json
Labels: Technology request

#6298 Replace png to svg and other fixes
  src/drivers/webextension/images/icons/Boutiq.png
  src/drivers/webextension/images/icons/Boutiq.svg
  src/drivers/webextension/images/icons/Catch.png
  src/drivers/webextension/images/icons/Catch.svg
  src/drivers/webextension/images/icons/Deliverr.png
  src/drivers/webextension/images/icons/Deliverr.svg
  src/drivers/webextension/images/icons/Marker.png
  src/drivers/webextension/images/icons/Marker.svg
  src/drivers/webextension/images/icons/Measured.png
  src/drivers/webextension/images/icons/Measured.svg
  src/drivers/webextension/images/icons/Mokka.png
  src/drivers/webextension/images/icons/Mokka.svg
  src/drivers/webextension/images/icons/Simpl.png
  src/drivers/webextension/images/icons/Simpl.svg
  src/drivers/webextension/images/icons/Transcend.png
  src/drivers/webextension/images/icons/Transcend.svg
  src/technologies/b.json
  src/technologies/c.json
  src/technologies/d.json
  src/technologies/e.json
  src/technologies/m.json
  src/technologies/r.json
  src/technologies/s.json
  src/technologies/t.json
Labels: Performance

#6308 Update Prebid / advertising
  src/technologies/p.json
Labels: Bug

#6310 Add PayPal Credit / bnpl #4500
  src/technologies/p.json
Labels: Technology request

#6311 Add Recomify / shopify-app #5853
  src/drivers/webextension/images/icons/Recomify.png
  src/technologies/r.json
Labels: Technology request

#6312 Add Cozy AntiTheft / shopify app #5854
  src/drivers/webextension/images/icons/Cozy AntiTheft.png
  src/technologies/c.json
Labels: Technology request

#6314 Add Beam OutSell, AfterSell / shopify-app #5858, #5871
  src/drivers/webextension/images/icons/AfterSell.svg
  src/drivers/webextension/images/icons/Beam.svg
  src/technologies/b.json
Labels: Technology request

#6317 Add EraofEcom apps / shopify-app #5859
  src/drivers/webextension/images/icons/EraofEcom.png
  src/technologies/e.json
Labels: Technology request

#6318 Add Emotive / marketing automation #5860
  src/drivers/webextension/images/icons/Emotive.svg
  src/technologies/e.json
Labels: Technology request

#6319 Add FullContact / analytics #5865
  src/drivers/webextension/images/icons/FullContact.svg
  src/technologies/f.json
Labels: Technology request
