Repository wappalyzer/wappalyzer, pull requests merged in 2022-11, with the labels that each got.

#6930 Add Naive UI / ui-frameworks
  src/drivers/webextension/images/icons/Hyva Themes.svg
  src/drivers/webextension/images/icons/Hyva.svg
  src/drivers/webextension/images/icons/Naive UI.svg
  src/technologies/h.json
  src/technologies/n.json
Labels: Technology request

#6934 Add CallTrackingMetrics / analytics
  src/drivers/webextension/images/icons/CallTrackingMetrics.svg
  src/technologies/c.json
Labels: Technology request

#6935 Update ClickFunnels / page-builders
  src/technologies/c.json
Labels: Bug

#6936 Add Granim.js / js-lib
  src/technologies/g.json
Labels: Technology request

#6938 Add Ubiliz / ecommerce, widget
  src/drivers/webextension/images/icons/Ubiliz.svg
  src/drivers/webextension/images/icons/Ubuntu.png
  src/drivers/webextension/images/icons/Ubuntu.svg
  src/technologies/u.json
Labels: Technology request, Performance

#6939 Add Upfluence / affiliate programs
  src/drivers/webextension/images/icons/Upfluence.svg
  src/technologies/u.json
Labels: Technology request

#6940 Add Hatena Blog / blogs #6933
  src/drivers/webextension/images/icons/Hatena.svg
  src/technologies/h.json
Labels: Technology request

#6941 Add Shoefitr.io / personalisation #6142
  src/drivers/webextension/images/icons/Shoefitr.io.svg
  src/technologies/s.json
Labels: Technology request

#6943 Add 51.LA / analytics, Update 8base / paas
  src/drivers/webextension/images/icons/51.LA.png
  src/drivers/webextension/images/icons/8base-logo.png
  src/drivers/webextension/images/icons/8base.svg
  src/technologies/_.json
Labels: Technology request, Performance

#6948 Add MySiteNow / page-builders
  src/drivers/webextension/images/icons/MySiteNow.png
  src/technologies/m.json
Labels: Technology request

#6944 Add PrimeReact, PrimeVue, PrimeNG / ui-frameworks
  src/drivers/webextension/images/icons/PrimeNG.svg
  src/drivers/webextension/images/icons/PrimeReact.svg
  src/drivers/webextension/images/icons/PrimeVue.svg
  src/technologies/p.json
Labels: Technology request

#6963 Add vxe-table / js-lib
  src/drivers/webextension/images/icons/vxe-table.png
  src/technologies/v.json
Labels: Technology request

#6964 Add CRM+ / crm
  src/drivers/webextension/images/icons/CRM+.png
  src/drivers/webextension/images/icons/Criteo.svg
  src/technologies/c.json
  src/technologies/r.json
Labels: Technology request, Bug

#6965 Update HCL Digital Experience / cms
  src/technologies/h.json
Labels: Bug

#6972 Add SprintHub / marketing-automation
  src/drivers/webextension/images/icons/SprintHub.svg
  src/technologies/s.json
Labels: Technology request

#6973 Add Rocketfy / ecommerce, page-builders
  src/drivers/webextension/images/icons/Rocketfy.svg
  src/technologies/r.json
Labels: Technology request

#6975 Add Infoset / crm, livechat
  src/drivers/webextension/images/icons/Infoset.svg
  src/technologies/i.json
Labels: Technology request

#6976 Add SimpleSAMLphp / authentication
  src/technologies/s.json
Labels: Technology request

#6977 Update imperia CMS / cms
  src/technologies/i.json
Labels: Bug, Performance

#6978 Add Salesnauts / ecommerce
  src/drivers/webextension/images/icons/Salesnauts.png
  src/technologies/s.json
Labels: Technology request

#6979 Update Storyblock / cms
  src/technologies/s.json
Labels: Bug

#6980 Update Twitter Emoji / font-scripts
  src/technologies/t.json
Labels: Bug

#6981 Update RightJS / js-framework
  src/technologies/r.json
Labels: Bug

#6982 Add Empretienda / ecommerce
  src/drivers/webextension/images/icons/Empretienda.png
  src/technologies/e.json
Labels: Technology request

#6983 Add Canvas LMS / lms
  src/drivers/webextension/images/icons/Canvas LMS.svg
  src/technologies/c.json
Labels: Technology request

#6968 Add uPlot / js-graphics
  src/drivers/webextension/images/icons/uPlot.png
  src/technologies/u.json
Labels: Technology request

#6974 Add Aument / email, cart-abandonment
  src/drivers/webextension/images/icons/Aument.svg
  src/technologies/a.json
Labels: Technology request

#6986 Add Obsidian Publish / documentation
  src/drivers/webextension/images/icons/Obsidian Publish.svg
  src/technologies/o.json
Labels: Technology request

#6987 Add _hyperscript / js-lib
  src/drivers/webextension/images/icons/_hyperscript.png
  src/technologies/_.json
Labels: Technology request

#6993 Update Tebex / ecommerce
  src/technologies/t.json
Labels: Bug

#6994 Update VTEX / ecommerce
  src/technologies/v.json
Labels: Bug

#6995 Add DreamApply / recruitment-staffing,miscellaneous
  src/drivers/webextension/images/icons/DreamApply.png
  src/technologies/d.json
Labels: Technology request

#6996 Add Channel.io / live-chat,crm
  src/drivers/webextension/images/icons/Channel.io.png
  src/technologies/c.json
Labels: Technology request

#6997 Update Tailwind CSS / ui-framework
  src/technologies/t.json
Labels: Bug

#6998 Add StatusCast / issue-trackers #6990
  src/drivers/webextension/images/icons/StatusCast.svg
  src/technologies/s.json
Labels: Technology request

#6999 Update CakePHP / web-framework
  src/drivers/webextension/images/icons/CakePHP.png
  src/drivers/webextension/images/icons/CakePHP.svg
  src/technologies/c.json
Labels: Performance

#7001 Add FullCalendar / widget
  src/drivers/webextension/images/icons/FullCalendar.png
  src/technologies/f.json
Labels: Technology request

#7002 Update Vue.js / javascript-frameworks
  src/technologies/v.json
Labels: Bug

#7003 Add Salesforce Marketing Cloud products, Remove Pardot
  src/drivers/webextension/images/icons/Pardot.png
  src/technologies/p.json
  src/technologies/s.json
Labels: Technology request, Bug

#7022 Add KZ locales
  src/drivers/webextension/_locales/kz/messages.json
Labels: Feature request

#7027 Update October CMS / cms
  src/technologies/o.json
Labels: Bug

#7030 Add Centra / ecommerce
  src/drivers/webextension/images/icons/Centra.svg
  src/technologies/c.json
Labels: Technology request

#7031 Add Sitepark IES,InfoSite / cms
  src/drivers/webextension/images/icons/Sitepark.png
  src/technologies/s.json
Labels: Technology request

#7034 Update Fleksa / Reservations & delivery
  src/technologies/f.json
Labels: Bug

#7035 Add Kiliba / marketing-automation
  src/drivers/webextension/images/icons/Kiliba.svg
  src/technologies/k.json
Labels: Technology request

#7033 Add Crikle / live-chat
  src/drivers/webextension/images/icons/Crikle.svg
  src/technologies/c.json
Labels: Technology request

#7032 Add Seko OmniReturns / returns
  src/drivers/webextension/images/icons/Seko OmniReturns.png
  src/technologies/s.json
Labels: Technology request

#7037 Add Suncel / cms
  src/drivers/webextension/images/icons/Suncel.svg
  src/technologies/s.json
Labels: Technology request

#7038 Add Doppler / email, Doppler Forms, for WooComerce / plugins
  src/drivers/webextension/images/icons/Doppler.svg
  src/technologies/d.json
Labels: Technology request

#7048 Update Mapbox GL JS / maps
  src/technologies/m.json
Labels: Bug

#7053 Update Vercel / paas
  src/technologies/v.json
Labels: Bug

#7119 Fix icons #7117
  src/drivers/webextension/images/icons/WebAssembly.svg
  src/drivers/webextension/images/icons/Webgains.svg
  src/drivers/webextension/images/icons/vue-storefront.svg
  src/drivers/webextension/images/icons/webflow.svg
Labels: Bug

#7143 Update Optimizely product, Add Optimizely Commerce
  src/drivers/webextension/images/icons/optimizely-cms.svg
  src/technologies/e.json
  src/technologies/o.json
Labels: Technology request, Bug

#7142 Update Gumroad detection
  src/drivers/webextension/images/icons/Gumroad.svg
  src/technologies/g.json
Labels: Bug

#7141 Update Sitecore / cms
  src/technologies/s.json
Labels: Bug

#7127 Add Nextra Detection
  src/technologies/n.json
Labels: Technology request

#7121 Update Elementor / page-builder, wp-plugin #6966
  src/technologies/e.json
Labels: Bug, Performance

#7120 Add Swiffy Slider / js-lib #7089
  src/drivers/webextension/images/icons/Swiffy Slider.svg
  src/technologies/s.json
Labels: Technology request

#7118 Update Blackbaud CRM / crm
  src/drivers/webextension/images/icons/Blackbaud.png
  src/technologies/b.json
Labels: Bug

#7116 Add CoreMedia Content Cloud / cms, dsm
  src/drivers/webextension/images/icons/CoreMedia Content Cloud.svg
  src/technologies/c.json
Labels: Technology request

#7100 Add Systeme.io / marketing-automation
  src/drivers/webextension/images/icons/Systeme.io.svg
  src/technologies/s.json
Labels: Technology request

#7099 Add CiviCRM / crm, Add CiviCRM plugins/ wp-plugin
  src/drivers/webextension/images/icons/CiviCRM.png
  src/technologies/c.json
Labels: Technology request

#7095 Add daisyUI / ui-frameworks
  src/drivers/webextension/images/icons/daisyUI.png
  src/technologies/d.json
Labels: Technology request

#7080 AOS Detection using HTML DOM
  src/technologies/a.json
Labels: Bug

#7036 added australian call tracking providers
  src/drivers/webextension/images/icons/Avanser.svg
  src/drivers/webextension/images/icons/Delacon.png
  src/technologies/a.json
  src/technologies/d.json
  src/technologies/v.json
Labels: Technology request
