Repository wappalyzer/wappalyzer, pull requests merged in 2022-12, with the labels that each got.

#7166 Update Simple Machines Forum / forums
  src/drivers/webextension/images/icons/Simple Machines Forum.png
  src/technologies/s.json
Labels: Bug, Performance

#7165 Update Cowboy / web-server
  src/technologies/c.json
Labels: Bug

#7164 Update DHTMLX / js-lib
  src/drivers/webextension/images/icons/DHTMLX.png
  src/technologies/d.json
Labels: Bug

#7163 Add Cwicly / wp-plugin
  src/drivers/webextension/images/icons/Cwicly.png
  src/technologies/c.json
Labels: Technology request

#7125 Add Tally Detection
  src/drivers/webextension/images/icons/Tally.svg
  src/technologies/t.json
Labels: Technology request

#7177 Update Wagtail / cms
  src/drivers/webextension/images/icons/Wagtail.svg
  src/technologies/w.json
Labels: Bug

#7180 Update MyBB / forums #7179
  src/technologies/m.json
Labels: Bug

#7181 Add Shopify apps #6004
  src/drivers/webextension/images/icons/Reserve In-Store.svg
  src/drivers/webextension/images/icons/TawkTo.png
  src/drivers/webextension/images/icons/TawkTo.svg
  src/technologies/f.json
  src/technologies/p.json
  src/technologies/r.json
  src/technologies/s.json
  src/technologies/t.json
Labels: Technology request

#7202 Add Binance Pay / Payment processors
  src/drivers/webextension/images/icons/Binance.svg
  src/technologies/b.json
Labels: Technology request

#7200 Update Optimizely Content Management / cms
  src/technologies/o.json
Labels: Bug

#7199 Add SocialJuice / reviews,widget
  src/drivers/webextension/images/icons/SocialJuice.svg
  src/technologies/s.json
Labels: Technology request

#7198 Fix locale folder name
  src/drivers/webextension/_locales/kk/messages.json
Labels: Bug

#7196 Update Choices / js-lib #7129
  src/technologies/c.json
Labels: Bug

#7195 Add Marketpath CMS / cms
  src/drivers/webextension/images/icons/Marketpath CMS.png
  src/technologies/m.json
Labels: Technology request

#7194 Add CactiveCloud / web-server
  src/drivers/webextension/images/icons/CactiveCloud.svg
  src/technologies/c.json
Labels: Technology request

#7193 Add Storeino / ecommerce
  src/drivers/webextension/images/icons/Storeino.png
  src/technologies/s.json
Labels: Technology request

#7189 NextAuthjs Authentication detection added for Next.js
  src/drivers/webextension/images/icons/Next-Auth.png
  src/technologies/n.json
Labels: Technology request

#7187 Add Apereo CAS / authentication
  src/drivers/webextension/images/icons/Apereo CAS.png
  src/technologies/a.json
Labels: Technology request

#7184 Add Gomag / ecommerce, Fix GoMage category / ecommerce-frontends
  src/drivers/webextension/images/icons/Gomag.svg
  src/technologies/g.json
Labels: Technology request, Bug

#7183 Add ScandiPWA / ecommerce-frontends
  src/drivers/webextension/images/icons/ScandiPWA.png
  src/technologies/s.json
Labels: Technology request

#7182 Improve previously added technologies
  src/drivers/webextension/images/icons/AdRoll.svg
  src/drivers/webextension/images/icons/Afosto.svg
  src/drivers/webextension/images/icons/Amiro.CMS.png
  src/drivers/webextension/images/icons/Apache JSPWiki.png
  src/drivers/webextension/images/icons/Apache Tomcat.svg
  src/drivers/webextension/images/icons/ApexPages.png
  src/drivers/webextension/images/icons/Apigee.svg
  src/drivers/webextension/images/icons/Glider.js.svg
  src/drivers/webextension/images/icons/acquia-cloud-platform.svg
  src/drivers/webextension/images/icons/amCharts.png
  src/drivers/webextension/images/icons/amCharts.svg
  src/drivers/webextension/images/icons/apigee.svg
  src/technologies/a.json
Labels: Bug, Performance

#7201 Add ReadSpeaker / widget
  src/drivers/webextension/images/icons/ReadSpeaker.svg
  src/technologies/r.json
Labels: Technology request

#7205 Add KPHP / programming-languages
  src/technologies/k.json
Labels: Technology request

#7206 Update PIXIjs / js-graphics
  src/technologies/p.json
Labels: Bug

#7207 Clutch Widget Detection added
  src/drivers/webextension/images/icons/clutch.svg
  src/technologies/c.json
Labels: Technology request

#7208 OrderGroove Detection Added
  src/drivers/webextension/images/icons/ordergroove.svg
  src/technologies/o.json
Labels: Technology request

#7209 Add ShopBase / cross-border, ecoomerce
  src/drivers/webextension/images/icons/ShopBase.svg
  src/technologies/s.json
Labels: Technology request

#7213 ReturnPrime trace added
  src/drivers/webextension/images/icons/return-prime.png
  src/technologies/r.json
Labels: Technology request

#7223 Add Bold Themes / wp-theme, Bold Page Builder / pg-builder, wp-plugin
  src/drivers/webextension/images/icons/Bold Page Builder.png
  src/drivers/webextension/images/icons/Bold Themes.png
  src/technologies/b.json
Labels: Technology request

#7224 Add Cloudify.store / Reservations & delivery
  src/drivers/webextension/images/icons/Cloudify.store.png
  src/technologies/c.json
Labels: Technology request

#7219 Roistat Trace Added
  src/drivers/webextension/images/icons/roistat.svg
  src/technologies/r.json
Labels: Technology request

#7220 Shareaholic Trace Added
  src/drivers/webextension/images/icons/shareaholic.svg
  src/technologies/s.json
Labels: Technology request

#7222 Instamojo - Payment Processor Trace Added
  src/drivers/webextension/images/icons/instamojo.svg
  src/technologies/i.json
Labels: Technology request

#7221 Automatad Trace Added
  src/drivers/webextension/images/icons/automatad.png
  src/technologies/a.json
Labels: Technology request

#7225 Bookly Trace Added
  src/drivers/webextension/images/icons/bookly.png
  src/technologies/b.json
Labels: Technology request

#7227 Webpushr Trace added
  src/drivers/webextension/images/icons/webpushr.svg
  src/technologies/w.json
Labels: Technology request

#7229 Honeybadger Trace Added
  src/drivers/webextension/images/icons/honey-badger.svg
  src/technologies/h.json
Labels: Technology request

#7231 Vuukle Trace Added
  src/drivers/webextension/images/icons/vuukle.svg
  src/technologies/v.json
Labels: Technology request

#7233 Add Skilljar (LMS)
  src/drivers/webextension/images/icons/skilljar.svg
  src/technologies/s.json
Labels: Technology request

#7234 ReadMe Trace Added
  src/drivers/webextension/images/icons/readme.svg
  src/technologies/r.json
Labels: Technology request

#7236 PaySafe Trace Added
  src/drivers/webextension/images/icons/paysafe.svg
  src/technologies/p.json
Labels: Technology request

#7237 Juspay Trace Added
  src/drivers/webextension/images/icons/juspay.svg
  src/technologies/j.json
Labels: Technology request

#7239 CanvasJs Trace Added
  src/drivers/webextension/images/icons/canvasjs.svg
  src/technologies/c.json
Labels: Technology request

#7240 Wazimo Trace Added
  src/drivers/webextension/images/icons/wazimo.png
  src/technologies/w.json
Labels: Technology request

#7241 AdRecover Trace Added
  src/drivers/webextension/images/icons/adrecover.png
  src/technologies/a.json
Labels: Technology request

#7242 Viafoura Trace Added
  src/drivers/webextension/images/icons/viafoura.svg
  src/technologies/v.json
Labels: Technology request

#7243 Update GeneratePress / wp-theme
  src/technologies/g.json
Labels: Bug

#7244 Update VWO / ab-test, analytics
  src/technologies/v.json
Labels: Bug

#7245 Wowza Trace Added
  src/drivers/webextension/images/icons/wowza.svg
  src/technologies/w.json
Labels: Technology request

#7246 Update MODX / cms
  src/drivers/webextension/images/icons/MODX.png
  src/drivers/webextension/images/icons/MODX.svg
  src/technologies/m.json
Labels: Bug, Performance

#7247 Add Showit / page-builders
  src/drivers/webextension/images/icons/Showit.svg
  src/technologies/s.json
Labels: Technology request

#7248 Add Webflow Ecommerce / ecom, Update Webflow / page-builders
  src/technologies/w.json
Labels: Technology request, Performance

#7250 Add Download Monitor / wp-plugin
  src/drivers/webextension/images/icons/Download Monitor.png
  src/technologies/d.json
Labels: Technology request

#7217 ButterCMS Trace added
  src/drivers/webextension/images/icons/butter-cms.svg
  src/technologies/b.json
Labels: Technology request

#7052 Update Shopify / ecommerce
  src/technologies/s.json
Labels: Bug
