Repository wappalyzer/wappalyzer, pull requests merged in 2023-02, with the labels that each got.

#7398 Fix DOM selector
  src/technologies/a.json
Labels: Bug

#7392 Add Replicache Detection
  src/drivers/webextension/images/icons/Replicache.svg
  src/technologies/r.json
Labels: Technology request

#7393 Add Statsig detection
  src/drivers/webextension/images/icons/Statsig.svg
  src/technologies/s.json
Labels: Technology request

#7395 Add AlumnIQ / fundraising-donations
  src/drivers/webextension/images/icons/AlumnIQ.svg
  src/technologies/a.json
Labels: Technology request

#7396 Update Divi / page-builders
  src/technologies/d.json
Labels: Bug

#7397 Add Revv / fundraising-donations
  src/drivers/webextension/images/icons/Revv.png
  src/technologies/r.json
Labels: Technology request

#7401 Add Aklamio / referral-marketing
  src/drivers/webextension/images/icons/Aklamio.svg
  src/technologies/a.json
Labels: Technology request

#7402 Add detection for WPML WordPress plugin
  src/drivers/webextension/images/icons/WPML.svg
  src/technologies/w.json
Labels: Technology request

#7403 Add Potions / personalisation
  src/drivers/webextension/images/icons/Potions.svg
  src/technologies/p.json
Labels: Technology request

#7405 Adding UniFi OS
  src/drivers/webextension/images/icons/UniFi_OS.png
  src/technologies/u.json
Labels: Technology request

#7406 Adding Hirschmann OS
  src/drivers/webextension/images/icons/hirschmann_OS.png
  src/technologies/h.json
Labels: Technology request

#7407 Add Viqeo / video-players
  src/drivers/webextension/images/icons/Viqeo.svg
  src/technologies/v.json
Labels: Technology request

#7408 Add Rawabit / page-builders
  src/drivers/webextension/images/icons/Rawabit.svg
  src/technologies/r.json
Labels: Technology request

#7409 Add Webasyst Shop-Script / ecommerce
  src/drivers/webextension/images/icons/Webasyst Shop-Script.svg
  src/technologies/w.json
Labels: Technology request

#7410 Add Layui / ui-frameworks
  src/drivers/webextension/images/icons/Layui.png
  src/technologies/l.json
Labels: Technology request

#7412 Add iyzico / payment-processors
  src/drivers/webextension/images/icons/iyzico.svg
  src/technologies/i.json
Labels: Technology request

#7413 Add ThimPress products / wp-plugin, lms
  src/drivers/webextension/images/icons/ThimPress.svg
  src/technologies/t.json
Labels: Technology request

#7414 Update Astro / js-framework #7411
  src/technologies/a.json
Labels: Bug

#7415 Update CodeMirror / editors #7388
  src/technologies/c.json
Labels: Bug

#7419 Add ShopiMind / marketing-automation
  src/drivers/webextension/images/icons/ShopiMind.svg
  src/drivers/webextension/images/icons/Visa.svg
  src/drivers/webextension/images/icons/visa.png
  src/technologies/s.json
  src/technologies/v.json
Labels: Technology request

#7418 Add Vnda / ecommerce
  src/drivers/webextension/images/icons/Vnda.svg
  src/drivers/webextension/images/icons/vk.svg
  src/technologies/v.json
Labels: Technology request

#7417 Update Contentful, GraphQL
  src/technologies/c.json
  src/technologies/g.json
Labels: Bug

#7416 Add Replit / development
  src/drivers/webextension/images/icons/Replit.svg
  src/technologies/r.json
Labels: Technology request

#7391 Add ISAY / cms
  src/drivers/webextension/images/icons/ISAY.png
  src/technologies/i.json
Labels: Technology request

#7423 Add EZproxy / web server
  src/technologies/e.json
Labels: Technology request

#7424 Add Spatie Laravel Cookie Consent / cookie-compliance
  src/technologies/s.json
Labels: Technology request

#7425 Update Storyblok / cms
  src/technologies/s.json
Labels: Bug

#7426 Add RedShop / ecommerce
  src/drivers/webextension/images/icons/RedShop.png
  src/drivers/webextension/images/icons/Redux.png
  src/drivers/webextension/images/icons/Redux.svg
  src/technologies/r.json
Labels: Technology request, Performance

#7427 Add NexusPHP / cms
  src/drivers/webextension/images/icons/NexusPHP.png
  src/technologies/n.json
Labels: Technology request

#7428 Featherlight WP Plugin Detection Added
  src/drivers/webextension/images/icons/WP_Featherlight.png
  src/technologies/w.json
Labels: Technology request

#7429 SuperPWA WP Plugin Trace Added
  src/drivers/webextension/images/icons/superpwa.png
  src/technologies/s.json
Labels: Technology request

#7433 Add WPS Visitor Counter / wordpress-plugins
  src/drivers/webextension/images/icons/WPS Visitor Counter.png
  src/technologies/w.json
Labels: Technology request

#7434 Add Azko CMS / cms
  src/drivers/webextension/images/icons/Azko CMS.svg
  src/technologies/a.json
Labels: Technology request

#7435 Add WP Live Visitor Counter / wp-plugin, widget
  src/technologies/w.json
Labels: Technology request

#7436 Add Stackable / page-builders,wp-plugin
  src/drivers/webextension/images/icons/Stackable.svg
  src/technologies/s.json
Labels: Technology request

#7437 Add Imunify360 / security #7432
  src/drivers/webextension/images/icons/Imunify360.svg
  src/technologies/i.json
Labels: Technology request

#7439 Update Materialize CSS / ui-framework
  src/drivers/webextension/images/icons/Materialize CSS.png
  src/drivers/webextension/images/icons/Materialize CSS.svg
  src/technologies/a.json
  src/technologies/m.json
Labels: Bug, Performance

#7440 Update Autoptimize / wp-plugin
  src/technologies/a.json
Labels: Bug

#7442 Update Cloudflare / cdn
  src/technologies/c.json
Labels: Bug

#7443 Add Splide / js-lib
  src/drivers/webextension/images/icons/Splide.svg
  src/technologies/s.json
Labels: Technology request

#7444 Add Ziggy library
  src/drivers/webextension/images/icons/Ziggy.png
  src/technologies/z.json
Labels: Technology request

#7446 Add Webolytics / analytics, affiliate-marketing
  src/drivers/webextension/images/icons/Webolytics.svg
  src/technologies/w.json
Labels: Technology request

#7447 Add Analyzee / analytics
  src/drivers/webextension/images/icons/Analyzee.svg
  src/technologies/a.json
Labels: Technology request

#7448 Add Vev / page-builders
  src/drivers/webextension/images/icons/Vev.svg
  src/technologies/v.json
Labels: Technology request

#7449 Add MadCap Software / content-curation
  src/drivers/webextension/images/icons/MadCap Software.svg
  src/technologies/m.json
Labels: Technology request

#7453 Add "Spatie Media Library Pro" detection
  src/drivers/webextension/images/icons/Spatie Media Library Pro.svg
  src/technologies/s.json
Labels: Technology request

#7454 Add FormBold detection
  src/drivers/webextension/images/icons/FormBold.svg
  src/technologies/f.json
Labels: Technology request

#7455 Add FlippingBook / widget
  src/drivers/webextension/images/icons/FlippingBook.svg
  src/technologies/f.json
Labels: Technology request

#7456 Update RankMath SEO / wp-plugin
  src/technologies/r.json
Labels: Bug

#7457 Add Oracle WebLogic Server / webserver
  src/technologies/o.json
Labels: Technology request

#7458 Update Page builders / priority
  src/categories.json
Labels: Feature request

#7460 Update PhpMyAdmin
  src/technologies/p.json
Labels: Bug

#7461 Adding Stackbit
  src/drivers/webextension/images/icons/stackbit.svg
  src/technologies/s.json
Labels: Technology request

#7462 Comeet Trace Added
  src/drivers/webextension/images/icons/comeet.svg
  src/technologies/c.json
Labels: Technology request

#7463 Add Slate / crm
  src/drivers/webextension/images/icons/Slate.svg
  src/technologies/s.json
Labels: Technology request

#7464 Add Insightly CRM / crm
  src/drivers/webextension/images/icons/Insightly.svg
  src/technologies/i.json
Labels: Technology request

#7465 Add Kadence WP Blocks / wp-plugin
  src/technologies/k.json
Labels: Technology request

#7466 Add Perfmatters / wp-plugin,performance
  src/drivers/webextension/images/icons/Perfmatters.svg
  src/technologies/p.json
Labels: Technology request

#7467 Add Flying Pages,Analytics,Images / wp-plugin, performance
  src/drivers/webextension/images/icons/Flying Pages.svg
  src/technologies/f.json
Labels: Technology request

#7468 Add Eloomi / lms
  src/drivers/webextension/images/icons/Eloomi.png
  src/technologies/e.json
Labels: Technology request
