Repository wappalyzer/wappalyzer, pull requests merged in 2023-06, with the labels that each got.

#7729 Add PlatinMarket / ecommerce
  src/drivers/webextension/images/icons/PlatinMarket.png
  src/technologies/p.json
Labels: Technology request

#7730 Add Vant / ui-frameworks
  src/drivers/webextension/images/icons/Vant.png
  src/technologies/v.json
Labels: Technology request

#7731 Add Tolt / affiliate-programs
  src/drivers/webextension/images/icons/Tolt.svg
  src/technologies/t.json
Labels: Technology request

#7732 Update Stackbit, Cloudinary
  src/technologies/c.json
  src/technologies/s.json
Labels: Bug

#7733 Add The Church Co / page-builders
  src/drivers/webextension/images/icons/The Church Co.png
  src/technologies/t.json
Labels: Technology request

#7702 Update Element UI / ui-frameworks #7652
  src/technologies/e.json
Labels: Bug, Performance

#7701 Add Microsoft Azure Maps / geolocation,maps
  src/technologies/m.json
Labels: Technology request

#7697 Add Very Good Security / security
  src/drivers/webextension/images/icons/Very Good Security.svg
  src/drivers/webextension/images/icons/ViaBill.png
  src/drivers/webextension/images/icons/ViaBill.svg
  src/technologies/v.json
Labels: Technology request

#7696 Update Google Maps / maps
  src/technologies/g.json
Labels: Bug

#7695 Update Lightbox / js-lib
  src/technologies/l.json
Labels: Bug, Performance

#7694 Add RND / ecommerce
  src/drivers/webextension/images/icons/RND.png
  src/technologies/r.json
Labels: Technology request

#7693 Update Backdrop / cms #7654
  src/drivers/webextension/images/icons/Backdrop.png
  src/drivers/webextension/images/icons/Backdrop.svg
  src/technologies/b.json
Labels: Bug

#7692 Add Pingdom Uptime Monitoring / issue-tracker, Update Pingdom RUM/ rum #7689
  src/technologies/p.json
Labels: Technology request, Bug

#7691 Fix DOM selector
  src/technologies/t.json
Labels: Bug

#7690 Improve Drupal Multisite detection
  src/technologies/d.json
Labels: Bug

#7687 Add WordPress Multisite
  src/technologies/w.json
Labels: Technology request

#7684 Add Gigalixir PaaS detection
  src/drivers/webextension/images/icons/Gigalixir.svg
  src/technologies/g.json
Labels: Technology request

#7683 Algolia Detection Improved & Version Detection added
  src/technologies/a.json
Labels: Bug

#7682 Add Kudobuzz detection
  src/drivers/webextension/images/icons/kudobuzz.svg
  src/technologies/k.json
Labels: Technology request

#7728 Add Akilli Ticaret / ecommerce
  src/drivers/webextension/images/icons/Akilli Ticaret.svg
  src/technologies/a.json
Labels: Technology request

#7727 Add Sirge / analytics, shopify-apps
  src/drivers/webextension/images/icons/Sirge.svg
  src/technologies/s.json
Labels: Technology request

#7726 Update LogRocket / analytics
  src/technologies/l.json
Labels: Bug

#7725 Add Hydra-Shield / reverse-proxies
  src/drivers/webextension/images/icons/Hydra-Shield.png
  src/technologies/h.json
Labels: Technology request

#7724 Update OpenLayers / maps
  src/drivers/webextension/images/icons/OpenLayers.png
  src/drivers/webextension/images/icons/OpenLayers.svg
  src/technologies/o.json
Labels: Performance

#7723 Update Yext / search-engine,miscellaneous
  src/technologies/y.json
Labels: Bug

#7722 Update Astro / static-site-generator
  src/technologies/a.json
Labels: Bug

#7721 Add v4Guard Checkpoint / security
  src/drivers/webextension/images/icons/v4Guard.svg
  src/technologies/v.json
Labels: Technology request

#7720 Add Azure Edge Network / miscellaneous
  src/technologies/a.json
Labels: Technology request

#7719 Add EasyGift / shopify-apps
  src/drivers/webextension/images/icons/EasyGift.png
  src/technologies/e.json
Labels: Technology request

#7718 Add Buy with Prime / miscellaneous
  src/technologies/b.json
Labels: Technology request

#7717 Add SNO Flex / wp-themes
  src/drivers/webextension/images/icons/SNO.svg
  src/technologies/s.json
Labels: Technology request

#7716 Add Tiktak Pro / ecommerce
  src/drivers/webextension/images/icons/Tiktak Pro.svg
  src/technologies/t.json
Labels: Technology request

#7715 Add Radix Ui / ui-frameworks
  src/drivers/webextension/images/icons/Radix UI.svg
  src/technologies/r.json
Labels: Technology request

#7712 Add Sleekplan / issue-trackers
  src/drivers/webextension/images/icons/Sleekplan.svg
  src/technologies/s.json
Labels: Technology request

#7711 Add Mighty Network / lms, message-board
  src/drivers/webextension/images/icons/Mighty Network.svg
  src/technologies/m.json
Labels: Technology request

#7709 Add Hubalz / analytics
  src/drivers/webextension/images/icons/Hubalz.png
  src/technologies/h.json
Labels: Technology request

#7708 Add Lemon Squeezy / payment-processors
  src/drivers/webextension/images/icons/Lemon Squeezy.svg
  src/technologies/l.json
Labels: Technology request

#7707 Update Yotpo / loyalty, reviews
  src/technologies/y.json
Labels: Bug

#7706 Add Web Wiz Forums / message-boards
  src/technologies/w.json
Labels: Technology request

#7705 Add Linen / message-boards
  src/drivers/webextension/images/icons/Linen.svg
  src/technologies/l.json
Labels: Technology request

#7704 Update Stackbit / page-builders
  src/technologies/s.json
Labels: Bug

#7703 Add WEBrick / web-server #7700
  src/drivers/webextension/images/icons/Ruby on Rails.png
  src/drivers/webextension/images/icons/Ruby on Rails.svg
  src/technologies/r.json
  src/technologies/w.json
Labels: Technology request

#7755 Add IP2Location.io / geolocation
  src/drivers/webextension/images/icons/IP2Location.io.svg
  src/technologies/i.json
Labels: Technology request

#7754 Update Pimcore / cms,ecomm
  src/technologies/p.json
Labels: Bug

#7753 Add HockeyStack / analytics
  src/drivers/webextension/images/icons/HockeyStack.svg
  src/technologies/h.json
Labels: Technology request

#7751 Add Container Media Group / advertising
  src/drivers/webextension/images/icons/Container Media Group.svg
  src/technologies/c.json
Labels: Technology request

#7750 Add Trustindex, Fix Rich Plugins / reviews
  src/drivers/webextension/images/icons/Rich Plugins.png
  src/technologies/r.json
  src/technologies/t.json
Labels: Technology request, Bug

#7749 Add Unas / ecommerce
  src/drivers/webextension/images/icons/Unas.svg
  src/technologies/u.json
Labels: Technology request

#7748 Update commercetools / ecommerce
  src/technologies/c.json
Labels: Bug

#7747 Add Passage / authentication
  src/drivers/webextension/images/icons/Passage.svg
  src/technologies/p.json
Labels: Technology request

#7746 Add PubLive / cms
  src/drivers/webextension/images/icons/PubLive.svg
  src/technologies/p.json
Labels: Technology request

#7745 Add Quickbutik / ecommerce
  src/drivers/webextension/images/icons/Quickbutik.svg
  src/technologies/q.json
Labels: Technology request

#7744 Add KAMAR / lms
  src/drivers/webextension/images/icons/KAMAR.svg
  src/technologies/k.json
  src/technologies/m.json
Labels: Technology request

#7743 Add Webeyez / analytics
  src/drivers/webextension/images/icons/Webeyez.png
  src/technologies/w.json
Labels: Technology request

#7742 Add Prepr / cms
  src/drivers/webextension/images/icons/Prepr.svg
  src/technologies/p.json
Labels: Technology request

#7740 Add Uvodo / ecommerce
  src/drivers/webextension/images/icons/Uvodo.svg
  src/technologies/u.json
Labels: Technology request

#7739 Update WebAssembly / pl
  src/technologies/w.json
Labels: Bug

#7738 Add Bootic / ecommerce
  src/drivers/webextension/images/icons/Bootic.svg
  src/technologies/b.json
Labels: Technology request

#7734 Add Acconsento.click / cookie-compliance
  src/drivers/webextension/images/icons/Acconsento.click.png
  src/technologies/a.json
Labels: Technology request
