Repository wappalyzer/wappalyzer, pull requests merged in 2023-08, with the labels that each got.

#7896 Fix cpes that are too long
  src/technologies/a.json
  src/technologies/o.json
  src/technologies/s.json
Labels: Bug

#7881 Update Mautic / marketing-automation
  src/technologies/m.json
Labels: Bug

#7882 Add Opigno LMS / lms
  src/drivers/webextension/images/icons/Opigno LMS.svg
  src/technologies/o.json
Labels: Technology request

#7883 Add Karte / a-b-testing, personalisation
  src/drivers/webextension/images/icons/Karte.png
  src/drivers/webextension/images/icons/Kartra.png
  src/drivers/webextension/images/icons/Kartra.svg
  src/technologies/k.json
Labels: Technology request, Performance

#7885 Add Tistory detection
  src/drivers/webextension/images/icons/Tistory.svg
  src/technologies/t.json
Labels: Technology request

#7886 Update Duda / cms,page-builder
  src/drivers/webextension/images/icons/Duda.svg
  src/drivers/webextension/images/icons/duda.png
  src/technologies/d.json
Labels: Bug, Performance

#7887 Update Swell, SweetAlert, SweetAlert2
  src/technologies/s.json
Labels: Bug, Performance

#7888 Add Docsify / documentation
  src/drivers/webextension/images/icons/Docsify.svg
  src/technologies/d.json
Labels: Technology request

#7889 Add Lume / static-site-generator
  src/drivers/webextension/images/icons/Lume.svg
  src/technologies/l.json
Labels: Technology request

#7890 Add Nogin / miscellaneous
  src/drivers/webextension/images/icons/Nogin.png
  src/technologies/n.json
Labels: Technology request

#7891 Add Zeabur / PaaS
  src/drivers/webextension/images/icons/zeabur.svg
  src/technologies/z.json
Labels: Technology request

#7897 Update Aegea / blogs
  src/technologies/a.json
Labels: Bug

#7900 Add Hashtag Labs / advertising
  src/drivers/webextension/images/icons/Hashtag Labs.svg
  src/technologies/h.json
Labels: Technology request

#7901 Update WebAssembly / pl
  src/technologies/w.json
Labels: Bug

#7902 Add Sitecore Experience Edge / caching, Experience Platform / cms
  src/technologies/s.json
Labels: Technology request

#7903 Add Knak / email
  src/drivers/webextension/images/icons/Knak.svg
  src/technologies/k.json
Labels: Technology request

#7904 Add Rosti / hosting
  src/drivers/webextension/images/icons/Rosti.png
  src/technologies/r.json
Labels: Technology request

#7907 Update Ionic, Ionicons / framework,fonts
  src/drivers/webextension/images/icons/Ionic.svg
  src/drivers/webextension/images/icons/Ionicons.png
  src/drivers/webextension/images/icons/Ionicons.svg
  src/drivers/webextension/images/icons/ionic.png
  src/technologies/i.json
Labels: Performance

#7908 Add Header Bidding Ai / advertising
  src/drivers/webextension/images/icons/Header Bidding Ai.svg
  src/technologies/h.json
Labels: Technology request

#7909 Update Contentful / cms
  src/technologies/c.json
Labels: Bug

#7910 Add Summernote / editors
  src/drivers/webextension/images/icons/Summernote.svg
  src/technologies/s.json
Labels: Technology request

#7913 Add LearnDash / LMS, wp-plugin
  src/drivers/webextension/images/icons/LearnDash.svg
  src/technologies/l.json
Labels: Technology request

#7914 Add Isso / comment-systems
  src/technologies/i.json
Labels: Technology request

#7915 Update Sylius / ecommerce
  src/technologies/s.json
Labels: Bug

#7916 Update Salla / ecommerce
  src/technologies/s.json
Labels: Bug

#7917 Add WP Portfolio / wordpress-plugins
  src/drivers/webextension/images/icons/WP Portfolio.svg
  src/technologies/w.json
Labels: Technology request

#7918 Add Visual Portfolio / wp-plugin
  src/drivers/webextension/images/icons/Visual Portfolio.svg
  src/technologies/v.json
Labels: Technology request

#7919 Update Sitecore / cms
  src/technologies/s.json
Labels: Bug

#7921 Add 42stores / ecommerce
  src/drivers/webextension/images/icons/42stores.svg
  src/technologies/_.json
Labels: Technology request

#7922 Add Adobe Experience Manager Franklin / cms
  src/drivers/webextension/images/icons/Adobe Experience Manager Franklin.svg
  src/technologies/a.json
Labels: Technology request

#7923 Add Assertive Yield / advertising
  src/drivers/webextension/images/icons/Assertive Yield.svg
  src/technologies/a.json
Labels: Technology request

#7925 Update SvelteKit / ui-frameworks
  src/technologies/s.json
Labels: Bug

#7926 Update Google AdSense / advertising
  src/technologies/g.json
Labels: Bug

#7927 Add Kicksite / crm
  src/drivers/webextension/images/icons/Kicksite.png
  src/technologies/k.json
Labels: Technology request

#7928 Fix htlbid entry
  src/technologies/h.json
Labels: Bug
