Repository wappalyzer/wappalyzer, pull requests merged in 2023-07, with the labels that each got.

#7667 Add Ultimate Bulletin Board / message-boards
  src/technologies/u.json
Labels: Technology request

#7679 Add Front-Commerce detection
  src/drivers/webextension/images/icons/front-commerce.svg
  src/technologies/f.json
Labels: Technology request

#7757 taboola json changes
  src/technologies/t.json
Labels: Bug

#7758 Add E-Com Plus / ecommerce-frontends
  src/drivers/webextension/images/icons/E-Com Plus.svg
  src/technologies/e.json
Labels: Technology request

#7759 Add Apache APISIX / web-servers
  src/drivers/webextension/images/icons/Apache APISIX.svg
  src/technologies/a.json
Labels: Technology request

#7760 Update Firebase / development
  src/technologies/f.json
Labels: Bug

#7761 Add Payplug / payment-processors
  src/drivers/webextension/images/icons/Payplug.svg
  src/technologies/p.json
Labels: Technology request

#7762 Add AbhiCMS / cms
  src/technologies/a.json
Labels: Technology request

#7763 Update Mantine / ui-frameworks #7756
  src/technologies/m.json
Labels: Bug, Performance

#7765 Added technology: Microsoft .NET ClickOnce
  src/technologies/c.json
Labels: Technology request

#7766 Add Blotout EdgeTag / marketing-automation
  src/drivers/webextension/images/icons/Blotout.svg
  src/technologies/b.json
Labels: Technology request

#7769 Add ElkArte / message-boards #7767
  src/drivers/webextension/images/icons/ElkArte.png
  src/technologies/e.json
Labels: Technology request

#7773 Add Brimble / PaaS
  src/drivers/webextension/images/icons/brimble.svg
  src/technologies/b.json
Labels: Technology request

#7774 Colbass Trace Detection added
  src/drivers/webextension/images/icons/colbass.png
  src/technologies/c.json
Labels: Technology request

#7775 Vectary Detection added
  src/drivers/webextension/images/icons/vectary.svg
  src/technologies/v.json
Labels: Technology request

#7782 Fix DOM selector
  src/technologies/l.json
Labels: Bug

#7787 Add Craftum / page-builders #7674
  src/drivers/webextension/images/icons/Craftum.svg
  src/technologies/c.json
Labels: Technology request

#7788 Add genezio / development
  src/drivers/webextension/images/icons/genezio.svg
  src/technologies/g.json
Labels: Technology request

#7789 Remove duplicated word from Cloudflare Browser Insights descriptions
  src/technologies/c.json
Labels: Bug

#7779 Add WayForPay detection
  src/drivers/webextension/images/icons/WayForPay.svg
  src/technologies/w.json
Labels: Technology request

#7780 Replace `Spatie` logo with the SVG version
  src/drivers/webextension/images/icons/Spatie.png
  src/drivers/webextension/images/icons/Spatie.svg
  src/technologies/s.json
Labels: Performance

#7790 Add LlamaLink Cloud Server / web-servers
  src/drivers/webextension/images/icons/LlamaLink.png
  src/technologies/l.json
Labels: Technology request

#7792 Add ID5 detection
  src/drivers/webextension/images/icons/ID5.svg
  src/technologies/i.json
Labels: Technology request

#7793 Moat update
  src/drivers/webextension/images/icons/Moat.svg
  src/technologies/m.json
  src/technologies/o.json
Labels: Bug

#7796 Add Magixite / accessibility #7794
  src/drivers/webextension/images/icons/Magixite.png
  src/technologies/m.json
Labels: Technology request

#7797 Update Better Stack / issue-trackers #7795
  src/drivers/webextension/images/icons/Better Stack.svg
  src/drivers/webextension/images/icons/Better Uptime.svg
  src/technologies/b.json
Labels: Bug

#7798 Add Shoppub / ecommerce
  src/drivers/webextension/images/icons/Shoppub.svg
  src/technologies/s.json
Labels: Technology request

#7799 Update Omeka / cms
  src/technologies/o.json
Labels: Bug

#7800 Update Storyblok / cms
  src/technologies/s.json
Labels: Bug

#7802 Add Progress MOVEit / miscellaneous
  src/drivers/webextension/images/icons/Progress.svg
  src/technologies/p.json
Labels: Technology request

#7803 Update Imperva detection
  src/technologies/i.json
Labels: Bug

#7805 Add Beehiiv / blogs, Beehiiv RSS / feed-readers
  src/drivers/webextension/images/icons/Beehiiv.svg
  src/technologies/b.json
Labels: Technology request

#7806 Add ActBlue / fundraising-donations
  src/drivers/webextension/images/icons/ActBlue.svg
  src/technologies/a.json
Labels: Technology request

#7807 Add ApexChat / live-chat
  src/drivers/webextension/images/icons/ApexChat.svg
  src/technologies/a.json
Labels: Technology request

#7808 Update MantisBT / issue-tracker
  src/drivers/webextension/images/icons/MantisBT.png
  src/technologies/m.json
Labels: Bug

#7809 Add Skyflow / security
  src/drivers/webextension/images/icons/Skyflow.svg
  src/technologies/s.json
Labels: Technology request

#7810 Add Rubedo / cms
  src/technologies/r.json
Labels: Technology request

#7811 Add AlvandCMS / cms
  src/drivers/webextension/images/icons/AlvandCMS.png
  src/technologies/a.json
Labels: Technology request

#7814 Add Creatium / page-builders
  src/drivers/webextension/images/icons/Creatium.svg
  src/technologies/c.json
Labels: Technology request

#7815 Add authorize.net / payment-processors
  src/drivers/webextension/images/icons/authorize.net.svg
  src/technologies/a.json
Labels: Technology request

#7816 Add Datatrics / cdp, Update DataDome / security
  src/drivers/webextension/images/icons/DataDome.svg
  src/drivers/webextension/images/icons/Datatrics.svg
  src/drivers/webextension/images/icons/datadome.png
  src/technologies/d.json
Labels: Technology request, Performance

#7817 Update Salla / ecommerce
  src/drivers/webextension/images/icons/Salla.svg
  src/technologies/s.json
Labels: Bug

#7818 Fix SolidStart falas detection
  src/technologies/s.json
Labels: Bug

#7847 Update Loox / reviews(remove implies Shopify)
  src/technologies/l.json
Labels: Bug

#7848 Add SellersCommerce / ecommerce
  src/drivers/webextension/images/icons/SellersCommerce.png
  src/technologies/s.json
Labels: Technology request

#7849 Add OrderCast / ecommerce
  src/drivers/webextension/images/icons/OrderCast.svg
  src/technologies/o.json
Labels: Technology request

#7850 Update Cargo / page-builder
  src/technologies/c.json
Labels: Bug

#7851 Add GreatPages / page-builder
  src/drivers/webextension/images/icons/GreatPages.svg
  src/technologies/g.json
Labels: Technology request

#7852 Add Forethought Solve / widget
  src/drivers/webextension/images/icons/Forethought Solve.svg
  src/technologies/f.json
Labels: Technology request

#7853 Change mixpanel logo
  src/drivers/webextension/images/icons/Mixpanel.svg
Labels: Bug

#7855 Refactoring Sitefinity technology, by adding 'Progress' prefix
  src/technologies/p.json
  src/technologies/s.json
Labels: Bug

#7856 Update Handlebars / js-lib
  src/drivers/webextension/images/icons/Handlebars.png
  src/drivers/webextension/images/icons/Handlebars.svg
  src/technologies/h.json
Labels: Performance

#7860 Add HighLevel / marketing-automation
  src/drivers/webextension/images/icons/HighLevel.svg
  src/technologies/h.json
Labels: Technology request

#7861 Add Selless / ecommerce
  src/drivers/webextension/images/icons/Selless.svg
  src/technologies/s.json
Labels: Technology request

#7846 Add WooCommerce Subscriptions / wp-plugin
  src/technologies/w.json
Labels: Technology request

#7862 Add Fortinet FortiGate / security
  src/drivers/webextension/images/icons/Fortinet.svg
  src/technologies/f.json
Labels: Technology request

#7826 Add WeWeb / page-builders
  src/drivers/webextension/images/icons/WeWeb.svg
  src/technologies/w.json
Labels: Technology request

#7827 Add Navidium Shipping Protection / widget
  src/drivers/webextension/images/icons/Navidium.svg
  src/technologies/n.json
Labels: Technology request

#7829 Add Drubbit / ecommerce
  src/drivers/webextension/images/icons/Drubbit.svg
  src/technologies/d.json
Labels: Technology request

#7830 Add Alliance Auth / authentication
  src/drivers/webextension/images/icons/Alliance Auth.svg
  src/technologies/a.json
  src/technologies/j.json
Labels: Technology request

#7832 Add Wask / analytics
  src/drivers/webextension/images/icons/Wask.svg
  src/technologies/w.json
Labels: Technology request

#7836 Add PayGreen / payment-processors
  src/drivers/webextension/images/icons/PayGreen.svg
  src/technologies/p.json
Labels: Technology request

#7837 Add PRONOTE / lms
  src/drivers/webextension/images/icons/PRONOTE.png
  src/technologies/m.json
  src/technologies/p.json
Labels: Technology request

#7839 Update Plesk / hosting-panels
  src/drivers/webextension/images/icons/Pleroma.svg
  src/drivers/webextension/images/icons/Plesk.png
  src/drivers/webextension/images/icons/Plesk.svg
  src/technologies/p.json
Labels: Bug, Performance

#7840 Add BigCommerce B2B Edition / ecommerce
  src/drivers/webextension/images/icons/BigCommerce B2B Edition.svg
  src/technologies/b.json
Labels: Technology request

#7841 Add LeadChat / crm
  src/drivers/webextension/images/icons/LeadChat.svg
  src/technologies/l.json
Labels: Technology request

#7843 Add Proxmox VE / containers, Proxmox Mail Gateway / security
  src/drivers/webextension/images/icons/Proxmox.svg
  src/technologies/p.json
Labels: Technology request

#7844 Update Umbraco / cms
  src/drivers/webextension/images/icons/Umbraco.png
  src/drivers/webextension/images/icons/Umbraco.svg
  src/technologies/u.json
Labels: Bug, Performance

#7845 Add Sitecore Engagement Cloud / cdp
  src/technologies/s.json
Labels: Technology request

#7825 Add Sirvoy / appointment-scheduling
  src/drivers/webextension/images/icons/Sirvoy.svg
  src/technologies/s.json
Labels: Technology request

#7824 Add BookVisit / appointment-scheduling
  src/drivers/webextension/images/icons/BookVisit.png
  src/technologies/b.json
Labels: Technology request

#7821 Update Ibexa / cms
  src/technologies/e.json
  src/technologies/i.json
Labels: Bug

#7820 Add Glassix / live-chat #7819
  src/technologies/g.json
Labels: Technology request
