Repository wappalyzer/wappalyzer, pull requests merged in 2023-04, with the labels that each got.

#7568 Add RoadRunner detection
  src/drivers/webextension/images/icons/RoadRunner.svg
  src/technologies/r.json
Labels: Technology request

#7567 Add OpenSwoole detection
  src/drivers/webextension/images/icons/OpenSwoole.svg
  src/technologies/o.json
Labels: Technology request

#7571 Update ArvanCloud
  src/technologies/a.json
Labels: Bug

#7539 Add Bunny Fonts detection
  src/drivers/webextension/images/icons/Bunny.png
  src/drivers/webextension/images/icons/Bunny.svg
  src/technologies/b.json
Labels: Technology request

#7526 Add Relewise / personalisation
  src/drivers/webextension/images/icons/Relewise.svg
  src/technologies/r.json
Labels: Technology request

#7527 Add Doteasy Website Builder / page-builders, Add Doteasy / hosting
  src/drivers/webextension/images/icons/Doteasy.svg
  src/technologies/d.json
Labels: Technology request

#7528 Add Formli / form-builders
  src/drivers/webextension/images/icons/Formli.svg
  src/technologies/f.json
Labels: Technology request

#7532 Update Bulma / ui-frameworks
  src/technologies/b.json
Labels: Bug

#7533 Add Algolia DocSearch / widget
  src/drivers/webextension/images/icons/DocSearch.svg
  src/technologies/a.json
Labels: Technology request

#7534 Update Font Awesome / font scripts
  src/technologies/f.json
Labels: Bug, Performance

#7535 Add WP Automatic / wp-plugin
  src/drivers/webextension/images/icons/WP Automatic.png
  src/technologies/w.json
Labels: Technology request

#7536 Update OpenCart / ecommerce
  src/drivers/webextension/images/icons/OpenCart.png
  src/drivers/webextension/images/icons/OpenCart.svg
  src/technologies/o.json
Labels: Bug, Performance

#7537 Add Bigin / crm
  src/drivers/webextension/images/icons/Bigin.png
  src/technologies/b.json
Labels: Technology request

#7538 Add Peripl / analytics
  src/drivers/webextension/images/icons/Peripl.png
  src/technologies/p.json
Labels: Technology request

#7541 Update Sitecore / cms
  src/technologies/s.json
Labels: Bug

#7542 Update NextGEN Gallery / wp-plugin
  src/technologies/n.json
Labels: Bug

#7543 Add SearchiQ / search-engine
  src/drivers/webextension/images/icons/SearchiQ.svg
  src/technologies/s.json
Labels: Technology request

#7545 Add GPT AI Power / wp -plugin
  src/drivers/webextension/images/icons/GPT AI Power.png
  src/technologies/g.json
Labels: Technology request

#7546 Add Breakdance / page-builder
  src/drivers/webextension/images/icons/Breakdance.svg
  src/technologies/b.json
Labels: Technology request

#7547 Add E-monsite / cms
  src/drivers/webextension/images/icons/E-monsite.svg
  src/technologies/e.json
Labels: Technology request

#7548 Add FlyingPress / performance, wp-plugin
  src/drivers/webextension/images/icons/FlyingPress.svg
  src/technologies/f.json
Labels: Technology request

#7549 Add YunoHost / operating-systems
  src/drivers/webextension/images/icons/YunoHost.svg
  src/technologies/y.json
Labels: Technology request

#7550 Add Tapfiliate / affiliate-programs
  src/drivers/webextension/images/icons/Tapfiliate.svg
  src/technologies/t.json
Labels: Technology request

#7551 Add Fathershops / ecommerce
  src/drivers/webextension/images/icons/FatherShops.png
  src/technologies/f.json
Labels: Technology request

#7552 Add Alibaba Cloud Object Storage Service / iaas
  src/technologies/a.json
Labels: Technology request

#7553 Add Netdeal / marketing-automation
  src/drivers/webextension/images/icons/Netdeal.svg
  src/technologies/n.json
Labels: Technology request

#7554 Add Combodo iTop / issue-trackers, miscellaneous
  src/drivers/webextension/images/icons/Combodo iTop.svg
  src/technologies/c.json
Labels: Technology request

#7557 Add LandingPress / wp-theme
  src/drivers/webextension/images/icons/LandingPress.png
  src/technologies/l.json
Labels: Technology request

#7558 Add OTYS / recruitment-staffing
  src/drivers/webextension/images/icons/OTYS.svg
  src/technologies/o.json
Labels: Technology request

#7560 Add DigitalOcean Spaces / iaas, cdn
  src/drivers/webextension/images/icons/DigitalOcean.svg
  src/technologies/d.json
Labels: Technology request

#7561 Add Waitlist / widget
  src/drivers/webextension/images/icons/Waitlist.svg
  src/technologies/w.json
Labels: Technology request

#7562 Add PowerSchool / lms
  src/drivers/webextension/images/icons/PowerSchool.svg
  src/technologies/p.json
Labels: Technology request

#7570 Update technology Zyro to Hostinger Website Builder
  src/drivers/webextension/images/icons/Zyro.svg
  src/technologies/h.json
  src/technologies/z.json
Labels: Bug

#7575 Retype Trace Added
  src/drivers/webextension/images/icons/retype.svg
  src/technologies/r.json
Labels: Technology request

#7576 Captivate Trace Added
  src/drivers/webextension/images/icons/Captivate.fm.svg
  src/technologies/c.json
Labels: Technology request

#7581 Add Huddle / lms
  src/drivers/webextension/images/icons/Huddle.svg
  src/technologies/h.json
Labels: Technology request

#7582 Update Sylius / ecommerce
  src/technologies/s.json
Labels: Bug

#7583 Add Funnelish / page-builder
  src/drivers/webextension/images/icons/Funnelish.svg
  src/technologies/f.json
Labels: Technology request

#7584 Add Ycode / page-builder
  src/drivers/webextension/images/icons/Ycode.svg
  src/technologies/y.json
Labels: Technology request

#7585 Update Klevu / search-engines
  src/technologies/k.json
Labels: Bug

#7586 Add Motherhost / hosting
  src/drivers/webextension/images/icons/Motherhost.svg
  src/technologies/m.json
Labels: Technology request

#7587 Add UpSolution Zephyr / wp-theme
  src/drivers/webextension/images/icons/UpSolution.png
  src/technologies/u.json
Labels: Technology request

#7589 Add MDBootstrap WP theme / wp-theme
  src/technologies/m.json
Labels: Technology request

#7590 Update Elementor / page-builder, wp-plugin
  src/technologies/e.json
Labels: Bug

#7591 Add W3.CSS / ui-frameworks
  src/drivers/webextension/images/icons/W3.CSS.svg
  src/technologies/w.json
Labels: Technology request

#7594 Improve "Super Builder" detection
  src/technologies/s.json
Labels: Bug

#7596 Add June Analytics detection
  src/drivers/webextension/images/icons/June.svg
  src/technologies/j.json
Labels: Technology request

#7600 Add Mintlify / documentation, ssg #7574
  src/drivers/webextension/images/icons/Mintlify.svg
  src/technologies/m.json
Labels: Technology request

#7601 Change Fly.io category
  src/technologies/f.json
Labels: Bug

#7603 Add Bluestone PIM / DAM
  src/drivers/webextension/images/icons/Bluestone PIM.svg
  src/technologies/b.json
Labels: Technology request

#7604 Update Nacelle / ecommerce
  src/technologies/n.json
Labels: Bug

#7605 Update Stencil / web-components
  src/technologies/s.json
Labels: Bug

#7606 Add Arena / widget
  src/drivers/webextension/images/icons/Arena.svg
  src/technologies/a.json
Labels: Technology request

#7607 Add ShipStation / shipping carriers
  src/drivers/webextension/images/icons/ShipStation.svg
  src/technologies/s.json
Labels: Technology request

#7608 Add JUST / payment-processors
  src/drivers/webextension/images/icons/JUST.svg
  src/technologies/j.json
Labels: Technology request

#7609 Add Plasmic / page-builder
  src/drivers/webextension/images/icons/Plasmic.svg
  src/technologies/p.json
Labels: Technology request

#7599 Remixd Trace Added
  src/drivers/webextension/images/icons/remixd.svg
  src/technologies/r.json
Labels: Technology request

#7593 Render Trace Added
  src/drivers/webextension/images/icons/render.svg
  src/technologies/r.json
Labels: Technology request

#7565 Quilljs Rich Text Editor Trace Improved
  src/technologies/q.json
Labels: Bug

#7580 Add "Chicago Boss" detection
  src/drivers/webextension/images/icons/Chicago Boss.svg
  src/technologies/c.json
Labels: Technology request

#7611 Add ClientXCMS / cms
  src/drivers/webextension/images/icons/ClientXCMS.png
  src/drivers/webextension/images/icons/render.svg
  src/technologies/c.json
  src/technologies/r.json
Labels: Technology request

#7613 Add Cloudrexx / cms
  src/drivers/webextension/images/icons/Cloudrexx.svg
  src/technologies/c.json
Labels: Technology request

#7614 Add Efilli / cookie-compliance
  src/drivers/webextension/images/icons/Efilli.svg
  src/technologies/e.json
Labels: Technology request

#7615 Add Société des Avis Garantis / reviews , wp-plugin
  src/drivers/webextension/images/icons/Societe des Avis Garantis.svg
  src/technologies/s.json
Labels: Technology request

#7618 Add Pagefai CMS / cms
  src/drivers/webextension/images/icons/Pagefai.png
  src/technologies/p.json
Labels: Technology request

#7610 Update Odoo / cms
  src/drivers/webextension/images/icons/Odoo.png
  src/drivers/webextension/images/icons/Odoo.svg
  src/technologies/o.json
Labels: Bug

#7620 Update BugSnag
  src/drivers/webextension/images/icons/BugSnag.png
  src/drivers/webextension/images/icons/BugSnag.svg
  src/technologies/b.json
Labels: Bug

#7624 Add Redux Framework / wp-plugin, removed Extendify / wp-plugin
  src/drivers/webextension/images/icons/Extendify.svg
  src/drivers/webextension/images/icons/Redux Framework.svg
  src/technologies/e.json
  src/technologies/r.json
Labels: Technology request, Bug

#7627 Add Aniview Video Ad Player, Aniview Ad Server / video-payer, Ad
  src/drivers/webextension/images/icons/Aniview.png
  src/technologies/a.json
Labels: Technology request
