Repository wappalyzer/wappalyzer, pull requests merged in 2023-01, with the labels that each got.

#7302 Fixed JSON missing comma
  src/technologies/p.json
Labels: Bug

#7296 Update Apollo / js-lib
  src/technologies/a.json
Labels: Bug

#7297 Add Glide.js / js-lib
  src/drivers/webextension/images/icons/Glide.js.svg
  src/technologies/g.json
Labels: Technology request

#7303 Add Airtable / widget
  src/drivers/webextension/images/icons/Airtable.svg
  src/technologies/a.json
Labels: Technology request

#7304 Add Statuspal / issue-trackers
  src/drivers/webextension/images/icons/Statuspal.svg
  src/technologies/s.json
Labels: Technology request

#7308 TradingView Chart Library Trace added
  src/categories.json
  src/drivers/webextension/images/icons/trading_view.svg
  src/technologies/p.json
  src/technologies/t.json
Labels: Technology request

#7319 Zotabox Trace Added
  src/drivers/webextension/images/icons/zotabox.png
  src/technologies/z.json
Labels: Technology request

#7320 Noibu Error Tracking Trace Added
  src/drivers/webextension/images/icons/noibu.svg
  src/technologies/n.json
Labels: Technology request

#7322 Update DreamWeaver / editors
  src/technologies/d.json
Labels: Bug

#7323 Add Microsoft Visual Studio / development
  src/drivers/webextension/images/icons/Microsoft Visual Studio.svg
  src/technologies/m.json
Labels: Technology request

#7324 Add Siteimprove / analytics
  src/drivers/webextension/images/icons/Siteimprove.svg
  src/technologies/s.json
Labels: Technology request

#7325 Add Angie / web-server #7321
  src/technologies/a.json
  src/technologies/n.json
Labels: Technology request

#7326 Update Sitefinity / cms
  src/technologies/s.json
Labels: Bug

#7269 Conviva Trace Added
  src/drivers/webextension/images/icons/conviva.svg
  src/technologies/c.json
Labels: Technology request

#7271 ElementsKit - Elementor AddOn Trace Added
  src/drivers/webextension/images/icons/elementskit.svg
  src/technologies/e.json
Labels: Technology request

#7272 Master Slider Trace Added'
  src/drivers/webextension/images/icons/master_slider.png
  src/technologies/m.json
Labels: Technology request

#7273 JetElements - Elementor AddOn Trace Added
  src/drivers/webextension/images/icons/Crocoblock.svg
  src/technologies/c.json
Labels: Technology request

#7274 Ivory Searc WP Plugin Trace Added
  src/drivers/webextension/images/icons/ivory_searc.png
  src/technologies/i.json
Labels: Technology request

#7286 Add detection for WordPress themes Twenty Twenty-Two and Twenty Twenty-Three
  src/technologies/t.json
Labels: Technology request

#7290 Add AntiBot.Cloud / security #7285
  src/technologies/a.json
Labels: Technology request

#7291 Update Divi,Slider Revolution / versions
  src/technologies/d.json
  src/technologies/s.json
Labels: Bug

#7329 Add Vercel Analytics scriptSrc
  src/technologies/v.json
Labels: Bug

#7330 Add PostHog Detection
  src/drivers/webextension/images/icons/PostHog.svg
  src/technologies/p.json
Labels: Technology request

#7332 Add vite dom,js detection
  src/technologies/v.json
Labels: Bug

#7335 VentryShield Trace Added
  src/drivers/webextension/images/icons/ventry_shield.png
  src/technologies/v.json
Labels: Technology request

#7336 RenderBetter Trace Added
  src/drivers/webextension/images/icons/renderbetter.svg
  src/technologies/r.json
Labels: Technology request

#7337 Storybook Trace Added
  src/drivers/webextension/images/icons/storybook.svg
  src/technologies/s.json
Labels: Technology request

#7338 Add GenerateBlocks / page-builder,wp-plugin
  src/drivers/webextension/images/icons/GenerateBlocks.svg
  src/technologies/g.json
Labels: Technology request

#7339 Update Three.js / js-graph
  src/drivers/webextension/images/icons/Three.js.svg
  src/drivers/webextension/images/icons/three.js.png
  src/technologies/a.json
  src/technologies/t.json
Labels: Bug

#7340 Add Expivi / augmented-reality
  src/drivers/webextension/images/icons/Expivi.svg
  src/technologies/e.json
Labels: Technology request

#7341 Add Cloudlfare Workers
  src/drivers/webextension/images/icons/Cloudflare Workers.svg
  src/technologies/c.json
Labels: Technology request

#7342 Add Vultr
  src/drivers/webextension/images/icons/Vultr.svg
  src/technologies/v.json
Labels: Technology request

#7344 Add Apple MapKit JS / maps
  src/technologies/a.json
Labels: Technology request

#7345 Add Loom
  src/drivers/webextension/images/icons/Loom.svg
  src/technologies/l.json
Labels: Technology request

#7348 Cloudflare Stream Detection added
  src/technologies/c.json
Labels: Technology request

#7351 Add amplitude js detection
  src/technologies/a.json
Labels: Bug

#7355 Angie Detection Improved
  src/technologies/a.json
Labels: Bug

#7356 Element Detection Added
  src/drivers/webextension/images/icons/elementio.svg
  src/technologies/e.json
Labels: Technology request

#7357 Landbot Detection Added
  src/drivers/webextension/images/icons/landbot.svg
  src/technologies/l.json
Labels: Technology request

#7358 Twilio Authy Detection added
  src/drivers/webextension/images/icons/twilio_authy.svg
  src/technologies/t.json
Labels: Technology request

#7359 Truepush Detection added
  src/drivers/webextension/images/icons/truepush.svg
  src/technologies/t.json
Labels: Technology request

#7363 Yandex SmartCaptcha Detection added
  src/drivers/webextension/images/icons/yandex_smartcaptcha.svg
  src/technologies/y.json
Labels: Technology request

#7366 Add Zeald / ecommerce
  src/drivers/webextension/images/icons/Zeald.png
  src/technologies/z.json
Labels: Technology request

#7367 Update UmiJs, Depict
  src/technologies/d.json
  src/technologies/u.json
Labels: Bug

#7343 Add uMarketingSuite / personalisation, analytics
  src/drivers/webextension/images/icons/uMarketingSuite.svg
  src/technologies/u.json
Labels: Technology request

#7368 Update Docusaurus / documentation, ssg
  src/technologies/d.json
Labels: Bug

#7371 Add Adobe Portfolio / page-builders
  src/drivers/webextension/images/icons/Adobe Portfolio.svg
  src/technologies/a.json
Labels: Technology request

#7372 Add MetroUI / ui-frameworks
  src/technologies/m.json
Labels: Technology request

#7373 Add Squadata / retargeting, Update Squadded, Sqreen
  src/drivers/webextension/images/icons/Sqreen.png
  src/drivers/webextension/images/icons/Sqreen.svg
  src/drivers/webextension/images/icons/Squadata.png
  src/drivers/webextension/images/icons/Squadded.png
  src/drivers/webextension/images/icons/Squadded.svg
  src/technologies/s.json
Labels: Technology request, Bug, Performance

#7374 Add Anthology Encompass / crm
  src/drivers/webextension/images/icons/Anthology.svg
  src/technologies/a.json
Labels: Technology request

#7375 Add Community Funded / fundraising-donations
  src/drivers/webextension/images/icons/Community Funded.png
  src/technologies/c.json
Labels: Technology request

#7376 Add LGC / cms
  src/drivers/webextension/images/icons/LGC.png
  src/technologies/l.json
Labels: Technology request

#7377 Add Pico CSS / ui-frameworks
  src/drivers/webextension/images/icons/Pico CSS.svg
  src/technologies/p.json
Labels: Technology request

#7378 Add Vendre / ecommerce
  src/drivers/webextension/images/icons/Vendre.png
  src/technologies/v.json
Labels: Technology request

#7379 Add 5centsCDN / cdn
  src/drivers/webextension/images/icons/5centsCDN.svg
  src/technologies/_.json
Labels: Technology request

#7383 Add Checkly / issue-trackers, Fix Checkfront - category #7381
  src/drivers/webextension/images/icons/Checkly.svg
  src/technologies/c.json
Labels: Technology request, Bug

#7385 Update three.js / js-graph
  src/technologies/t.json
Labels: Bug

#7386 Add Formaloo / form-builders, Update Fork CMS, FormAssembly
  src/drivers/webextension/images/icons/FormAssembly.svg
  src/drivers/webextension/images/icons/Formaloo.svg
  src/technologies/f.json
Labels: Technology request

#7382 Added BigDataCloud API
  src/drivers/webextension/images/icons/BigDataCloud-IPGeolocation.svg
  src/technologies/b.json
Labels: Technology request
