Repository wappalyzer/wappalyzer, pull requests merged in 2023-05, with the labels that each got.

#7655 Add Philomena / message-boards(imageboard)
  src/drivers/webextension/images/icons/Philomena.svg
  src/technologies/p.json
Labels: Technology request

#7657 Add Skolengo CMS detection
  src/drivers/webextension/images/icons/Skolengo.svg
  src/technologies/s.json
Labels: Technology request

#7658 Cosmic Headless CMS Trace Detection Added
  src/drivers/webextension/images/icons/cosmicjs.svg
  src/technologies/c.json
Labels: Technology request

#7659 aHrefs SEO Traffic Monitoring Widget Trace Added
  src/drivers/webextension/images/icons/ahrefs.svg
  src/technologies/a.json
Labels: Technology request

#7660 Add Confiant / security
  src/drivers/webextension/images/icons/Confiant.svg
  src/technologies/c.json
Labels: Technology request

#7661 Update MailChimp / email marketing
  src/technologies/m.json
Labels: Bug, Performance

#7662 Update UmiJs / js framweorks
  src/technologies/u.json
Labels: Bug

#7663 Add Buttonizer / widget
  src/drivers/webextension/images/icons/Buttonizer.svg
  src/technologies/b.json
Labels: Technology request

#7665 Add FraudLabs Pro / security
  src/drivers/webextension/images/icons/FraudLabs Pro.png
  src/technologies/f.json
Labels: Technology request

#7666 Add Brilliant Web-to-Lead / wp-plugin
  src/drivers/webextension/images/icons/Brilliant Web-to-Lead.png
  src/technologies/b.json
Labels: Technology request

#7669 Vuex Detection Added
  src/technologies/v.json
Labels: Technology request

#7670 Add Preline UI / ui-frameworks
  src/drivers/webextension/images/icons/Preline UI.svg
  src/technologies/p.json
Labels: Technology request

#7672 Add Mapbox.js / maps
  src/technologies/m.json
Labels: Technology request

#7673 Add Sprig plugin / miscellaneous
  src/drivers/webextension/images/icons/Sprig plugin.svg
  src/technologies/s.json
Labels: Technology request

#7678 Improve AdOpt detection
  src/technologies/a.json
Labels: Bug

#7685 add language: Vietnamese
  src/drivers/webextension/_locales/vi/messages.json
Labels: Feature request

#7636 Add ipbase / geolocation
  src/drivers/webextension/images/icons/ipbase.svg
  src/technologies/i.json
Labels: Technology request

#7638 Update Triggerbee / personalisation, analytics
  src/drivers/webextension/images/icons/Triggerbee.png
  src/drivers/webextension/images/icons/Triggerbee.svg
  src/technologies/t.json
Labels: Bug

#7639 Fix Sucuri - remove WordPress requirement
  src/drivers/webextension/images/icons/sucuri.png
  src/drivers/webextension/images/icons/sucuri.svg
  src/technologies/s.json
Labels: Bug

#7647 Update CrownPeak properties
  src/technologies/c.json
Labels: Bug

#7649 Blitz.js Detection added
  src/drivers/webextension/images/icons/blitzjs.svg
  src/technologies/b.json
Labels: Technology request

#7650 LottieFile Version Detection with JS Object
  src/technologies/l.json
Labels: Bug

#7653 Add THRON / dam
  src/drivers/webextension/images/icons/THRON.png
  src/technologies/t.json
Labels: Technology request

#7656 ApexPages was using Cloudflare's icon by mistake. This commit changes…
  src/technologies/a.json
Labels: Bug
